name: Build and Deploy
on:
  push:
    branches:
      - source
  watch:
    types: [started]
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.actor == github.event.repository.owner.login
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2

      # - name: Install ğŸ“¦
      #   run: npm ci --production

      - name: Build ğŸ”§
        run: node scripts/build.js

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          BRANCH: main
          FOLDER: dist
