name: Build and Deploy
on:
  push:
    branches:
      - source
  watch:
    types: [started]
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.actor == github.event.repository.owner.login
    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v2

      # - name: Install ðŸ“¦
      #   run: npm ci --production

      # - name: Build ðŸ”§
      #   run: npm run build

      - name: Test
        run: |
          mkdir dist
          echo Hello > dist/index.html

      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          BRANCH: main
          FOLDER: dist
